### ISSUE TITLE
Objects.py - intcast(val) ValueError on Windows 7

### ISSUE THREAD

**Issue by kieranjol** [simsong/dfxml#29]
I am running walk_to_dfxml.py on Windows 7 (python 2.7.10) and I receive the following error which looks like a zero of Long type is produced, rather than an int or string?

```
python ./walk_to_dfxml.py -d
DEBUG:Objects.pyc:val = 0L
Traceback (most recent call last):
  File "./walk_to_dfxml.py", line 205, in <module>
    main()
  File "./walk_to_dfxml.py", line 185, in main
    fobj = filepath_to_fileobject(filepath)
  File "./walk_to_dfxml.py", line 49, in filepath_to_fileobject
    fobj.populate_from_stat(sobj)
  File "C:\Users\Ingest_1\Downloads\dfxml-master\dfxml-master\python\Objects.py"
, line 2151, in populate_from_stat
    self.inode = s.st_ino
  File "C:\Users\Ingest_1\Downloads\dfxml-master\dfxml-master\python\Objects.py"
, line 2545, in inode
    self._inode = _intcast(val)
  File "C:\Users\Ingest_1\Downloads\dfxml-master\dfxml-master\python\Objects.py"
, line 121, in _intcast
    raise ValueError("Received a non-int-castable value.  Expected an integer or
 an integer as a string.")
ValueError: Received a non-int-castable value.  Expected an integer or an intege
r as a string.
```

**Comment by kieranjol** [comment]
Thank you so much!

**Comment by ajnelson-nist** [comment]
Hi again!  Apologies for the delayed reply, something looked a bit off when I was checking re-production conditions.  The short of that story is a [documentation change](https://bugs.python.org/issue32878).  I was then at a conference last week.

Thank you for reporting this.  I'll push the fix now.

**Comment by kieranjol** [comment]
Very cool, thank you! And I appreciate the thorough explanation.
